=== Pret-a-LLOD/Fintan/doc/reference/TBX-resources/TBXcoreStructV02.dtd
<!-- start schema here tbx_core.dtd -->
<!-- TBXcoreStructV02.dtd -->
<!-- note: see XCS for values of type on meta data-categories and for values of
xml:lang -->
<!-- =================================================================================
SOME USEFUL ENTITIES THAT ARE REFERENCED BELOW
================================================================================== -->
<!ENTITY % basicText '(#PCDATA | hi)*'>
<!ENTITY % noteText '(#PCDATA | hi | foreign | bpt | ept | ph)*'>
<!ENTITY % auxInfo '(descrip | descripGrp | admin | adminGrp | transacGrp | note | ref
| xref)*' >
<!ENTITY % noteLinkInfo '(admin | adminGrp | transacGrp | note | ref | xref)*' >
<!-- Entities that define common sets of attributes -->
<!ENTITY % impIDLang '
id ID #IMPLIED
xml:lang CDATA #IMPLIED
'>
<!ENTITY % impIDType '
id ID #IMPLIED
type CDATA #IMPLIED
'>
<!ENTITY % impIDLangTypTgtDtyp '
id ID #IMPLIED
xml:lang CDATA #IMPLIED
type CDATA #REQUIRED
target IDREF #IMPLIED
datatype CDATA #IMPLIED
'>
<!-- ================================================================================
ELEMENTS USED FOR TEXT MARKUP
================================================================================ -->
<!ELEMENT hi (#PCDATA) >
<!ATTLIST hi
type CDATA #IMPLIED
target IDREF #IMPLIED
xml:lang CDATA #IMPLIED
>
<!ELEMENT foreign %noteText; >
<!ATTLIST foreign
id ID #IMPLIED
xml:lang CDATA #IMPLIED
>
<!ELEMENT bpt (#PCDATA) >
<!ATTLIST bpt
i CDATA #IMPLIED
type CDATA #IMPLIED

>
<!ELEMENT ept (#PCDATA) >
<!ATTLIST ept
i CDATA #IMPLIED
>
<!ELEMENT ph (#PCDATA) >
<!ATTLIST ph
type CDATA #IMPLIED
>
<!-- ================================================================================
ELEMENTS NEEDED FOR TERMINOLOGICAL ENTRIES (IN ALPHABETICAL ORDER)
================================================================================ -->
<!ELEMENT admin %noteText; >
<!ATTLIST admin
%impIDLangTypTgtDtyp;
>
<!ELEMENT adminGrp (admin, (adminNote|note|ref|xref)*) >
<!ATTLIST adminGrp
id ID #IMPLIED
>
<!ELEMENT adminNote (#PCDATA) >
<!ATTLIST adminNote
%impIDLangTypTgtDtyp;
>
<!ELEMENT date (#PCDATA) >
<!ATTLIST date
id ID #IMPLIED
>
<!ELEMENT descrip %noteText; >
<!ATTLIST descrip
%impIDLangTypTgtDtyp;
>
<!ELEMENT descripGrp (descrip, (descripNote|admin|adminGrp|transacGrp|note|ref|xref)*)
>
<!ATTLIST descripGrp
id ID #IMPLIED
>
<!ELEMENT descripNote (#PCDATA) >
<!ATTLIST descripNote
%impIDLangTypTgtDtyp;
>
<!ELEMENT langSet ((%auxInfo;), (tig | ntig)+) >
<!ATTLIST langSet
id ID #IMPLIED
xml:lang CDATA #REQUIRED
>
<!ELEMENT note %noteText; >
<!ATTLIST note %impIDLang;
>
<!ELEMENT ntig (termGrp, %auxInfo;) >
<!ATTLIST ntig
id ID #IMPLIED
>
<!ELEMENT ref (#PCDATA) >
<!ATTLIST ref
%impIDLangTypTgtDtyp;
>
<!ELEMENT term %basicText; >
<!ATTLIST term
id ID #IMPLIED
>
<!ELEMENT termComp (#PCDATA) >
<!ATTLIST termComp
%impIDLang;
>
<!ELEMENT termCompGrp (termComp, (termNote|termNoteGrp)*, %noteLinkInfo;) >
<!ATTLIST termCompGrp
id ID #IMPLIED
>
<!ELEMENT termCompList ((%auxInfo;), (termComp | termCompGrp)+) >
<!ATTLIST termCompList
id ID #IMPLIED
type CDATA #REQUIRED
>
<!ELEMENT termEntry ((%auxInfo;),(langSet+)) >
<!ATTLIST termEntry
id ID #IMPLIED
>
<!ELEMENT termGrp (term, (termNote|termNoteGrp)*, (termCompList)* ) >
<!ATTLIST termGrp
id ID #IMPLIED
>
<!ELEMENT termNote %noteText; >
<!ATTLIST termNote
%impIDLangTypTgtDtyp;
>
<!ELEMENT termNoteGrp (termNote, %noteLinkInfo;) >
<!ATTLIST termNoteGrp
id ID #IMPLIED
>
<!ELEMENT tig (term, (termNote)*, %auxInfo;) >
<!ATTLIST tig
id ID #IMPLIED
>
<!ELEMENT transac (#PCDATA) >
<!ATTLIST transac
%impIDLangTypTgtDtyp;
>
<!ELEMENT transacGrp (transac, (transacNote|date|note|ref|xref)* ) >
<!ATTLIST transacGrp
id ID #IMPLIED
>

<!ELEMENT transacNote (#PCDATA) >
<!ATTLIST transacNote
%impIDLangTypTgtDtyp;
>
<!ELEMENT xref (#PCDATA) >
<!ATTLIST xref
%impIDType;
target CDATA #REQUIRED
>
<!--
===================================================================================
OTHER ELEMENTS (in hierarchical order)
===================================================================================
-->
<!ELEMENT martif (martifHeader, text) > <!-- *** starting element *** -->
<!ATTLIST martif
type CDATA #REQUIRED
xml:lang CDATA #REQUIRED
>
<!ELEMENT martifHeader (fileDesc, encodingDesc?, revisionDesc?) >
<!ATTLIST martifHeader
id ID #IMPLIED
>
<!ELEMENT p %noteText; > <!-- p is used in several header elements -->
<!ATTLIST p
id ID #IMPLIED
type (DCSName|XCSURI|XCSContent) #IMPLIED
xml:lang CDATA #IMPLIED
>
<!ELEMENT fileDesc (titleStmt?, publicationStmt?, sourceDesc+) >
<!ATTLIST fileDesc
id ID #IMPLIED
>
<!ELEMENT titleStmt (title, note*) >
<!ATTLIST titleStmt
%impIDLang;
>
<!ELEMENT title (#PCDATA) >
<!ATTLIST title
%impIDLang;
>
<!ELEMENT publicationStmt (p+) >
<!ATTLIST publicationStmt
id ID #IMPLIED
>
<!ELEMENT sourceDesc (p+) >
<!ATTLIST sourceDesc
%impIDLang;
>
<!ELEMENT encodingDesc (p+) >
<!ATTLIST encodingDesc
id ID #IMPLIED

>
<!ELEMENT revisionDesc (change+) >
<!ATTLIST revisionDesc
%impIDLang;
>
<!ELEMENT change (p+) >
<!ATTLIST change
%impIDLang; >
<!ELEMENT text (body, back?) >
<!ATTLIST text
id ID #IMPLIED
>
<!ELEMENT body (termEntry+) >
<!ATTLIST body
id ID #IMPLIED
>
<!ELEMENT back ((refObjectList)*) >
<!ATTLIST back
id ID #IMPLIED
>
<!ELEMENT refObjectList (refObject+) >
<!ATTLIST refObjectList
id ID #IMPLIED
type CDATA #REQUIRED
>
<!ELEMENT refObject ((itemSet | itemGrp | item)+) >
<!ATTLIST refObject
id ID #IMPLIED
>
<!ELEMENT item %noteText; >
<!ATTLIST item
%impIDType;
>
<!ELEMENT itemGrp (item, %noteLinkInfo;)>
<!ATTLIST itemGrp
id ID #IMPLIED
>
<!ELEMENT itemSet ((item | itemGrp)+)>
<!ATTLIST itemSet
%impIDType;
>
<!-- end -->
<!-- end schema here -->

=== Pret-a-LLOD/Fintan/backend/tbx2rdf/samples/TBX2RDF_demo_2.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE martif SYSTEM "http://www.ttt.org/oscarstandards/tbx/TBXcoreStructV02.dtd">
<martif type="TBX" xml:lang="en">
  <martifHeader>
    <fileDesc>
      <sourceDesc>
        <p>Applied linguistics</p>
      </sourceDesc>
    </fileDesc>
    <encodingDesc>
      <p type="XCSURI">https://demo.taas-project.eu/tbx/taas.xcs</p>
    </encodingDesc>
  </martifHeader>
  <text>
    <body>
	<termEntry id="TaaS-2643576">
  <descrip type="subjectField">TaaS-2000</descrip>
  <langSet xml:lang="en">
    <ntig>
      <termGrp>
        <term>bilingual dictionary</term>
        <termNote type="MSD">JJ NN</termNote>
        <termCompList type="lemma">
          <termCompGrp>
            <termComp>bilingual</termComp>
            <termNote type="partOfSpeech">adjective</termNote>
          </termCompGrp>
          <termCompGrp>
            <termComp>dictionary</termComp>
            <termNote type="partOfSpeech">noun</termNote>
            <termNote type="grammaticalNumber">singular</termNote>
          </termCompGrp>
        </termCompList>
      </termGrp>
      <descripGrp>
        <descrip type="surface">bilingual dictionary</descrip>
        <descripNote type="surfaceForm">bilingual dictionary</descripNote>
        <descripNote type="surfaceMSD">JJ NN</descripNote>
        <descripNote type="normalizedForm">bilingual dictionary</descripNote>
        <descripNote type="normalizedMSD">JJ NN</descripNote>
        <descripNote type="lemma">bilingual dictionary</descripNote>
      </descripGrp>
      <transacGrp>
        <transac type="transactionType">origination</transac>
        <transacNote type="responsibility">Extracted automatically by TaaS</transacNote>
        <date>2014-09-28</date>
      </transacGrp>
      <xref target="http://taas.eurotermbank.com/extractor" type="xSource" />
      <descripGrp>
        <descrip type="context">encyclopedia , monolingual versus<hi>bilingual dictionary</hi>, general versus technical</descrip>
      </descripGrp>
      <descripGrp>
        <descrip type="context">use of the<hi>bilingual dictionary</hi>in all its</descrip>       
      </descripGrp>
      <transacGrp>
        <transac type="transactionType">approval</transac>
        <transacNote type="responsibility">GornostayT</transacNote>
        <date>2014-09-28T13:58:11.974Z</date>
      </transacGrp>
      <admin type="status">approved</admin>
    </ntig>
  </langSet>  
</termEntry>
<termEntry id="TaaS-2643577">
  <descrip type="subjectField">TaaS-2000</descrip>
  <langSet xml:lang="en">
    <ntig>
      <termGrp>
        <term>unilingual</term>
        <termNote type="MSD">JJ NN</termNote>
        <termCompList type="lemma">
          <termCompGrp>
            <termComp>unilingual</termComp>
            <termNote type="partOfSpeech">adjective</termNote>
          </termCompGrp>
          <termCompGrp>
            <termComp>counterpart</termComp>
            <termNote type="partOfSpeech">noun</termNote>
            <termNote type="grammaticalNumber">singular</termNote>
          </termCompGrp>
        </termCompList>
      </termGrp>
      <descripGrp>
        <descrip type="surface">unilingual counterpart</descrip>
        <descripNote type="surfaceForm">unilingual counterpart</descripNote>
        <descripNote type="surfaceMSD">JJ NN</descripNote>
        <descripNote type="normalizedForm">unilingual counterpart</descripNote>
        <descripNote type="normalizedMSD">JJ NN</descripNote>
        <descripNote type="lemma">unilingual counterpart</descripNote>
      </descripGrp>
      <transacGrp>
        <transac type="transactionType">origination</transac>
        <transacNote type="responsibility">Extracted automatically by TaaS</transacNote>
        <date>2014-09-28</date>
      </transacGrp>
      <xref target="http://taas.eurotermbank.com/extractor" type="xSource" />
      <descripGrp>
        <descrip type="context">respects than its<hi>unilingual counterpart</hi>, especially in</descrip>     
      </descripGrp>
      <transacGrp>
        <transac type="transactionType">modification</transac>
        <transacNote type="responsibility">GornostayT</transacNote>
        <date>2014-09-28T14:01:24.277Z</date>
      </transacGrp>
      <transacGrp>
        <transac type="transactionType">approval</transac>
        <transacNote type="responsibility">GornostayT</transacNote>
        <date>2014-09-28T14:01:24.278Z</date>
      </transacGrp>
      <admin type="status">approved</admin>
    </ntig>
  </langSet> 
</termEntry>
<termEntry id="TaaS-2643589">
  <descrip type="subjectField">TaaS-2000</descrip>
  <langSet xml:lang="en">
    <ntig>
      <termGrp>
        <term>specialized dictionary</term>
        <termNote type="MSD">JJ NN</termNote>
        <termCompList type="lemma">
          <termCompGrp>
            <termComp>specialized</termComp>
            <termNote type="partOfSpeech">adjective</termNote>
          </termCompGrp>
          <termCompGrp>
            <termComp>dictionary</termComp>
            <termNote type="partOfSpeech">noun</termNote>
            <termNote type="grammaticalNumber">singular</termNote>
          </termCompGrp>
        </termCompList>
      </termGrp>
      <descripGrp>
        <descrip type="surface">specialized dictionaries</descrip>
        <descripNote type="surfaceForm">specialized dictionaries</descripNote>
        <descripNote type="surfaceMSD">JJ NNS</descripNote>
        <descripNote type="normalizedForm">specialized dictionary</descripNote>
        <descripNote type="normalizedMSD">JJ NN</descripNote>
        <descripNote type="lemma">specialized dictionary</descripNote>
      </descripGrp>
      <descripGrp>
        <descrip type="surface">specialized dictionary</descrip>
        <descripNote type="surfaceForm">specialized dictionary</descripNote>
        <descripNote type="surfaceMSD">JJ NN</descripNote>
        <descripNote type="normalizedForm">specialized dictionary</descripNote>
        <descripNote type="normalizedMSD">JJ NN</descripNote>
        <descripNote type="lemma">specialized dictionary</descripNote>
      </descripGrp>
      <descripGrp>
        <descrip type="surface">Specialized dictionary</descrip>
        <descripNote type="surfaceForm">Specialized dictionary</descripNote>
        <descripNote type="surfaceMSD">JJ NN</descripNote>
        <descripNote type="normalizedForm">Specialized dictionary</descripNote>
        <descripNote type="normalizedMSD">JJ NN</descripNote>
        <descripNote type="lemma">specialized dictionary</descripNote>
      </descripGrp>
      <transacGrp>
        <transac type="transactionType">origination</transac>
        <transacNote type="responsibility">Extracted automatically by TaaS</transacNote>
        <date>2014-09-28</date>
      </transacGrp>
      <xref target="http://taas.eurotermbank.com/extractor" type="xSource" />
      <descripGrp>
        <descrip type="context">and evaluation of<hi>specialized dictionaries</hi>, i.e. dictionaries</descrip>       
      </descripGrp>
      <descripGrp>
        <descrip type="context">usually called a<hi>specialized dictionary</hi>or LSP dictionary and</descrip>      
      </descripGrp>
      <descripGrp>
        <descrip type="context">Monolingual learner 's dictionary<hi>Specialized dictionary</hi>( Picture dictionary ,</descrip>      
      </descripGrp>
      <transacGrp>
        <transac type="transactionType">approval</transac>
        <transacNote type="responsibility">GornostayT</transacNote>
        <date>2014-09-28T13:53:07.422Z</date>
      </transacGrp>
      <admin type="status">approved</admin>
      <note>Orthographic variant: specialised dictionary</note>
      <transacGrp>
        <transac type="transactionType">modification</transac>
        <transacNote type="responsibility">GornostayT</transacNote>
        <date>2014-09-28T13:54:09.112Z</date>
      </transacGrp>
    </ntig>
  </langSet>
  <langSet xml:lang="lv">
    <ntig>
      <termGrp>
        <term>specializēta vārdnīca</term>
      </termGrp>
      <transacGrp>
        <transac type="transactionType">origination</transac>
        <transacNote type="responsibility">GornostayT</transacNote>
        <date>2014-09-28T13:53:21.416Z</date>
      </transacGrp>
      <xref type="xSource" target="http://taas-project.eu/editor/GornostayT/4301" />
      <transacGrp>
        <transac type="transactionType">approval</transac>
        <transacNote type="responsibility">GornostayT</transacNote>
        <date>2014-09-28T13:53:21.421Z</date>
      </transacGrp>
      <admin type="status">approved</admin>
    </ntig>
  </langSet>
</termEntry>
</body>
  </text>
</martif>

=== Pret-a-LLOD/Fintan/samples/TaaS_entry_export_example_in_TBX.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE martif SYSTEM "http://www.ttt.org/oscarstandards/tbx/TBXcoreStructV02.dtd">
<martif type="TBX" xml:lang="en">
  <martifHeader>
    <fileDesc>
      <sourceDesc>
        <p>LOD_experiment</p>
      </sourceDesc>
    </fileDesc>
    <encodingDesc>
      <p type="XCSURI">http://www.ttt.org/oscarstandards/tbx/TBXXCS.xcs</p>
    </encodingDesc>
  </martifHeader>
  <text>
    <body><termEntry id="2151845">
  <descrip type="subjectField">TaaS-1500</descrip>
  <langSet xml:lang="lv" xmlns:xml="http://www.w3.org/XML/1998/namespace">
    <ntig>
      <termGrp>
        <term>globālais tīmeklis</term>
        <termCompList type="lemma" />
      </termGrp>
      <xref target="http://www.eurotermbank.com/Collection.aspx?collectionid=390#1121964" type="xSource">Angļu–latviešu–krievu informātikas termini</xref>
      <transacGrp>
        <transac type="transactionType">origination</transac>
        <transacNote type="responsibility">Extracted automatically by TaaS</transacNote>
        <date>2014-05-08</date>
      </transacGrp>
      <transacGrp>
        <transac type="transactionType">approval</transac>
        <transacNote type="responsibility">GornostayT</transacNote>
        <date>2014-05-16T14:50:42.018Z</date>
      </transacGrp>
      <admin type="status">approved</admin>
      <admin type="sourceIdentifier">http://www.eurotermbank.com/search.aspx?text=World%20Wide%20Web&amp;langfrom=en&amp;langto=lv&amp;where=etb&amp;advanced=false#pos=1</admin>
      <transacGrp>
        <transac type="transactionType">modification</transac>
        <transacNote type="responsibility">GornostayT</transacNote>
        <date>2014-05-16T14:59:00.814Z</date>
      </transacGrp>
    </ntig>
    <note>Microsoft Public Terminology Collection</note>
  </langSet>
  <langSet xml:lang="en" xmlns:xml="http://www.w3.org/XML/1998/namespace">
    <ntig>
      <termGrp>
        <term>World Wide Web</term>
        <termNote type="MSD">NNP NNP NNP</termNote>
        <termCompList type="lemma">
          <termCompGrp>
            <termComp>World</termComp>
            <termNote type="partOfSpeech">noun</termNote>
            <termNote type="grammaticalNumber">singular</termNote>
          </termCompGrp>
          <termCompGrp>
            <termComp>Wide</termComp>
            <termNote type="partOfSpeech">adjective</termNote>
            <termNote type="grammaticalNumber">singular</termNote>
          </termCompGrp>
          <termCompGrp>
            <termComp>Web</termComp>
            <termNote type="partOfSpeech">noun</termNote>
            <termNote type="grammaticalNumber">singular</termNote>
          </termCompGrp>
        </termCompList>
      </termGrp>
      <descripGrp>
        <descrip type="surface">World Wide Web</descrip>
        <descripNote type="surfaceForm">World Wide Web</descripNote>
        <descripNote type="surfaceMSD">NNP NNP NNP</descripNote>
        <descripNote type="normalizedForm">World Wide Web</descripNote>
        <descripNote type="normalizedMSD">NNP NNP NNP</descripNote>
        <descripNote type="lemma">World Wide Web</descripNote>
        <descripNote type="context">nature of the<hi>World Wide Web</hi>for communication in</descripNote>
        <descripNote type="file">About The Project.htm</descripNote>
      </descripGrp>
      <descripGrp>
        <descrip type="surface">World Wide Web</descrip>
        <descripNote type="surfaceForm">World Wide Web</descripNote>
        <descripNote type="surfaceMSD">NNP NNP NNP</descripNote>
        <descripNote type="normalizedForm">World Wide Web</descripNote>
        <descripNote type="normalizedMSD">NNP NNP NNP</descripNote>
        <descripNote type="lemma">World Wide Web</descripNote>
        <descripNote type="context">viability of the<hi>World Wide Web</hi>is paramount. In</descripNote>
        <descripNote type="file">About The Project.htm</descripNote>
      </descripGrp>
      <descripGrp>
        <descrip type="surface">World Wide Web</descrip>
        <descripNote type="surfaceForm">World Wide Web</descripNote>
        <descripNote type="surfaceMSD">NNP NNP NNP</descripNote>
        <descripNote type="normalizedForm">World Wide Web</descripNote>
        <descripNote type="normalizedMSD">NNP NNP NNP</descripNote>
        <descripNote type="lemma">World Wide Web</descripNote>
        <descripNote type="context">driven by the<hi>World Wide Web</hi>Consortium (W3C), an</descripNote>
        <descripNote type="file">About The Project.htm</descripNote>
      </descripGrp>
      <transacGrp>
        <transac type="transactionType">origination</transac>
        <transacNote type="responsibility">Extracted automatically by TaaS</transacNote>
        <date>2014-05-08</date>
      </transacGrp>
      <xref target="http://taas.eurotermbank.com/extractor" type="xSource" />
      <descripGrp>
        <descrip type="context">nature of the<hi>World Wide Web</hi>for communication in</descrip>
        <admin target="About The Project.htm" type="sourceIdentifier" />
      </descripGrp>
      <descripGrp>
        <descrip type="context">viability of the<hi>World Wide Web</hi>is paramount. In</descrip>
        <admin target="About The Project.htm" type="sourceIdentifier" />
      </descripGrp>
      <descripGrp>
        <descrip type="context">driven by the<hi>World Wide Web</hi>Consortium (W3C), an</descrip>
        <admin target="About The Project.htm" type="sourceIdentifier" />
      </descripGrp>
      <transacGrp>
        <transac type="transactionType">approval</transac>
        <transacNote type="responsibility">GornostayT</transacNote>
        <date>2014-05-16T14:50:08.467Z</date>
      </transacGrp>
      <admin type="status">approved</admin>
      <admin type="sourceIdentifier">http://www.eurotermbank.com/search.aspx?text=World%20Wide%20Web&amp;langfrom=en&amp;langto=lv&amp;where=etb&amp;advanced=false#pos=1</admin>
      <transacGrp>
        <transac type="transactionType">modification</transac>
        <transacNote type="responsibility">GornostayT</transacNote>
        <date>2014-05-16T14:59:00.821Z</date>
      </transacGrp>
    </ntig>
    <note>Microsoft Public Terminology Collection</note>
    <descrip type="definition">A set of interlinked documents in a hypertext system. The user enters the web through a home page.</descrip>
  </langSet>
</termEntry></body>
  </text>
</martif>

=== Pret-a-LLOD/Fintan/samples/simple_with_decomp_trans.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE martif SYSTEM "http://www.ttt.org/oscarstandards/tbx/TBXcoreStructV02.dtd">
<martif type="TBX" xml:lang="en">
  <martifHeader>
    <fileDesc>
      <sourceDesc>
        <p>Small example to test decomposition and transactions</p>
      </sourceDesc>
    </fileDesc>
    <encodingDesc>
      <p type="XCSURI">http://www.ttt.org/oscarstandards/tbx/TBXXCS.xcs</p>
    </encodingDesc>
  </martifHeader>
  <text>
    <body><termEntry id="2151845">
  <descrip type="subjectField">TaaS-1500</descrip>
   <langSet xml:lang="en" xmlns:xml="http://www.w3.org/XML/1998/namespace">
    <ntig>
      <termGrp>
        <term>World Wide Web</term>
        <termNote type="MSD">NNP NNP NNP</termNote>
        <termCompList type="lemma">
          <termCompGrp>
            <termComp>World</termComp>
            <termNote type="partOfSpeech">noun</termNote>
            <termNote type="grammaticalNumber">singular</termNote>
          </termCompGrp>
          <termCompGrp>
            <termComp>Wide</termComp>
            <termNote type="partOfSpeech">adjective</termNote>
            <termNote type="grammaticalNumber">singular</termNote>
          </termCompGrp>
          <termCompGrp>
            <termComp>Web</termComp>
            <termNote type="partOfSpeech">noun</termNote>
            <termNote type="grammaticalNumber">singular</termNote>
          </termCompGrp>
        </termCompList>
      </termGrp>
      <transacGrp>
        <transac type="transactionType">origination</transac>
        <transacNote type="responsibility">Extracted automatically by TaaS</transacNote>
        <date>2014-05-08</date>
      </transacGrp>
      <transacGrp>
        <transac type="transactionType">approval</transac>
        <transacNote type="responsibility">GornostayT</transacNote>
        <date>2014-05-16T14:50:42.018Z</date>
      </transacGrp>
      <admin type="status">approved</admin>
      <admin type="sourceIdentifier">http://www.eurotermbank.com/search.aspx?text=World%20Wide%20Web&amp;langfrom=en&amp;langto=lv&amp;where=etb&amp;advanced=false#pos=1</admin>
      <transacGrp>
        <transac type="transactionType">modification</transac>
        <transacNote type="responsibility">GornostayT</transacNote>
        <date>2014-05-16T14:59:00.814Z</date>
      </transacGrp>
    </ntig>
   </langSet>
</termEntry>
</body>
</text>
</martif>

=== Pret-a-LLOD/Fintan/samples/simple_with_decomposition.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE martif SYSTEM "http://www.ttt.org/oscarstandards/tbx/TBXcoreStructV02.dtd">
<martif type="TBX" xml:lang="en">
  <martifHeader>
    <fileDesc>
      <sourceDesc>
        <p>Small example to test decomposition</p>
      </sourceDesc>
    </fileDesc>
    <encodingDesc>
      <p type="XCSURI">http://www.ttt.org/oscarstandards/tbx/TBXXCS.xcs</p>
    </encodingDesc>
  </martifHeader>
  <text>
    <body><termEntry id="2151845">
  <descrip type="subjectField">TaaS-1500</descrip>
   <langSet xml:lang="en" xmlns:xml="http://www.w3.org/XML/1998/namespace">
    <ntig>
      <termGrp>
        <term>World Wide Web</term>
        <termCompList type="lemma">
          <termCompGrp>
            <termComp>World</termComp>
            <termNote type="partOfSpeech">noun</termNote>
            <termNote type="grammaticalNumber">singular</termNote>
          </termCompGrp>
          <termCompGrp>
            <termComp>Wide</termComp>
            <termNote type="partOfSpeech">adjective</termNote>
            <termNote type="grammaticalNumber">singular</termNote>
          </termCompGrp>
          <termCompGrp>
            <termComp>Web</termComp>
            <termNote type="partOfSpeech">noun</termNote>
            <termNote type="grammaticalNumber">singular</termNote>
          </termCompGrp>
        </termCompList>
      </termGrp>
    </ntig>
   </langSet>
</termEntry>
</body>
</text>
</martif>
